version: '3.8'

services: 
  web:
    build: .
    ports:
      - "8000:80"
    volumes: 
      - .:/code 
    environment:
      - DATABASE_URL=postgresql://postgres_user:postgres_password@localhost:postgres_port/db_name
    depends_on:
      - db 

  db:
    image: postgres:15
    volumes: 
      - db_data:/var/lib/postgresql/data 
    expose:
      - 5433
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    

volumes:
  db_data: 